### ISSUE TITLE
gwdetchar-overflow segments output option doesn't work

### ISSUE THREAD

**Issue by tjmassin** [ligovirgo/gwdetchar#1]
The sngl_burst output option worked fine, but using the segments or the integer-segments options throws an error at the file writing step:

gwdetchar-overflow 'Sep 12' 'Sep 13' 19 -i L1 -f L1_R -a L1:DMT-ANALYSIS_READY:1 -o segments

Traceback (most recent call last):
  File "/mnt/home1/detchar/opt/gwpysoft/bin/gwdetchar-overflow", line 117, in <module>
    segs.write(sys.stdout, format='ligolw')
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/astropy/io/registry.py", line 380, in write
    writer(data, *args, **kwargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/segments/io/ligolw.py", line 159, in write_ligolw
    return write_fileobj(xmldoc, fobj, gz=fobj.name.endswith('.gz'))
NameError: global name 'write_fileobj' is not defined

**Comment by duncanmmacleod** [comment]
Ah yes, this is related to gwpy/gwpy#140. I just need to install the latest bug-fix of gwpy to get things going.

**Comment by duncanmmacleod** [comment]
I have now updated gwpy on the LLO LDAS system, please try again and close this issue when appropriate.

**Comment by tjmassin** [comment]
Works now, thanks!
