### ISSUE TITLE
datafind isn't discovering the gaps that gwpy fails on

### ISSUE THREAD

**Issue by lauranuttall** [ligovirgo/gwdetchar#4]
gwdetchar-overflow 1124150912 1126051217 98 -f H1_R -i H1 -a H1:DMT-UP:1 -O integer-segments -o ER8A_20150821_20150912.xml --deep
Missing segments:
[1124562240 ... 1124562368)
[1125171648 ... 1125171776)
[1125178368 ... 1125178496)
[1125181376 ... 1125181632)
[1125182016 ... 1125182272)
[1125768064 ... 1125768192)
[1125769536 ... 1125769664)
[1125778048 ... 1125779264)
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft/bin/gwdetchar-overflow", line 98, in <module>
    start=seg[0], end=seg[1]-args.segment_end_pad)
  File "/home/detchar/opt/gwpysoft/lib64/python2.6/site-packages/astropy/io/registry.py", line 332, in read
    data = reader(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/timeseries/io/cache.py", line 131, in read_cache
    raise ValueError(msg)
ValueError: The cache given to TimeSeries.read has gaps in it in the following segments:
    [1124339712 ... 1124339776)

**Comment by duncanmmacleod** [comment]
for the record, this is still a reproduceable problem
